ci_service: travis_ci
coverage_service: coveralls
workspace: ASToast.xcodeworkspace
xcodeproj: ASToast.xcodeproj
scheme: ASToast
source_directory: ASToast/Source
# output_directory: code_coverage/xml_report