language: objective-c
xcode_workspace: ASToast.xcworkspace
osx_image: xcode7.3
xcode_scheme: ASToastTests
xcode_sdk: iphonesimulator9.0

branches:
 only: master

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/ASToast-*/
- rvm use $RVM_RUBY_VERSION

install: bundle

# script:
# - xcodebuild -workspace ASToast.xcworkspace -scheme ASToast -destination "platform=iOS Simulator,name=iPhone 6,OS=8.1" clean test

after_success: slather