language: objective-c
xcode_workspace: ASToast.xcworkspace
osx_image: xcode7.3
xcode_scheme: ASToast
xcode_sdk: iphonesimulator9.3

branches:
 only: master

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/ASToast-*/
- rvm use $RVM_RUBY_VERSION

install: bundle

script:
- xcodebuild -workspace ASToast.xcworkspace -scheme ASToast -destination "platform=iOS Simulator,name=iPhone 6,OS=9.3" clean test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty

after_success: slather