language: objective-c
osx_image: xcode7.3
xcode_project: ASToast.xcworkspace
xcode_scheme: ASToastTests
xcode_sdk: iphonesimulator9.0

branches:
 only:
 - master

script:
- xcodebuild \
  -workspace ASToast.xcworkspace \
  -scheme ASToastTests \
  -destination "platform=iOS Simulator,name=iPhone 6,OS=9.0" \
  clean test