language: objective-c
osx_image: xcode7.3
xcode_project: ASToast.xcworkspace
xcode_scheme: ASToastTests
xcode_sdk: iphonesimulator9.0

branches:
 only:
 - master

script:
- xcodebuild -workspace ASToast.xcworkspace -scheme ASToast -destination "platform=iOS Simulator,name=iPhone 6,OS=8.1" clean test

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f code_coverage/xml_report/cobertura.xml